export enum WEEK_DAY {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY'
}

export const COMMON_ERROR_CODE = [0, 401, 500]

export enum ROLE {
  MANAGER = 'MANAGER',
  SUB_MANAGER = 'SUB_MANAGER',
  OFFICER = 'OFFICER',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  HR = 'HR'
}
export enum GROUP {
  ADMIN = 'ADMIN'
}
export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE'
}
export enum EDIT_TYPE {
  SELF = 'SELF',
  ADMIN = 'ADMIN',
  HR = 'HR',
  DIRECT_MANAGER = 'DIRECT_MANAGER'
}
export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  DEACTIVE = 'DEACTIVE',
  INITIAL = 'INITIAL'
}
